export enum Role {
  EDITOR_IN_CHIEF = 'EDITOR_IN_CHIEF', // 편집장
  DEPUTY_EDITOR_IN_CHIEF = 'DEPUTY_EDITOR_IN_CHIEF', // 부편집장
  REPORTING_SENIOR_REPORTER = 'REPORTING_SENIOR_REPORTER', // 취재부 책임기자
  SENIOR_DESIGNER = 'SENIOR_DESIGNER', // 책임 디자이너
  DIGITAL_SENIOR_REPORTER = 'DIGITAL_SENIOR_REPORTER', // 디지털콘텐츠부 책임기자
  REPORTING_REPORTER = 'REPORTING_REPORTER', // 취재부 정기자
  DESIGNER = 'DESIGNER', // 디자이너
  DIGITAL_REPORTER = 'DIGITAL_REPORTER', // 디지털콘텐츠부 정기자
  CUB_REPORTER = 'CUB_REPORTER', // 수습기자
  ALUMNI = 'ALUMNI', // 거쳐간 사람들(나간 사람)
}
