name: Update Database (Dev)

on:
  push:
    branches:
      - main
    paths:
      - drizzle/**
  workflow_dispatch:

jobs:
  deploy:
    name: Migrate Database
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install Drizzle
        run: bun install

      - name: setup cloudflared
        uses: AnimMouse/setup-cloudflared@v2
        with:
          version: 'latest'

      - name: use Cloudflare
        env:
          TUNNEL_SERVICE_TOKEN_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
          TUNNEL_SERVICE_TOKEN_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
        run: |
          cloudflared access tcp --service-token-id ${{ secrets.CF_ACCESS_CLIENT_ID }} --service-token-secret ${{ secrets.CF_ACCESS_CLIENT_SECRET }} --hostname icarus-db.gistory.me --url localhost:32345 &
          sleep 5
          nc -zv localhost 32345

      - name: Migrate Database
        run: bunx drizzle-kit migrate
        env:
          DATABASE_URL: ${{ secrets.STG_DATABASE_URL }}
